# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module RSpec
end

module RSpec
  module Matchers
  end
end
