# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-rubyfmt` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-rubyfmt`.


# pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/version.rb:3
module RuboCop; end

# pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:6
module RuboCop::Cop; end

# pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:7
module RuboCop::Cop::Rubyfmt; end

# `rubyfmt` always places comments at the beginning of lines, so end-of-line
# disables cannot be used. The autocorrect for this lint
#
# @safety
#   This cop should only be moving comments and thus should be safe.
#   However, this is largely intended as a migration mechanism when first
#   adopting rubyfmt, so this is best-effort and may require some manual fixups.
#   That said, since it's moving comments only, those fixups should be pretty much entirely
#   caught by Rubocop, and most of the fixups should just be moving comments such that they
#   appropriately wrap the offending code.
#
#
# ```ruby
# # good
# bad_call!
#
# # bad
# ````
#
# pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:33
class RuboCop::Cop::Rubyfmt::NoEndOfLineRubocopDisables < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:39
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:61
  def autocorrect(corrector, comment); end

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:51
  def comment_only_line?(comment); end

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:55
  def register_offense(comment); end

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:47
  def same_line_directive?(comment); end
end

# pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:37
RuboCop::Cop::Rubyfmt::NoEndOfLineRubocopDisables::DISABLE_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rubyfmt#lib/rubocop/cop/rubyfmt/no_end_of_line_rubocop_disables.rb:36
RuboCop::Cop::Rubyfmt::NoEndOfLineRubocopDisables::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/version.rb:4
module RuboCop::Rubyfmt; end

# pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt.rb:7
class RuboCop::Rubyfmt::Error < ::StandardError; end

# A plugin that integrates rubocop-rubyfmt with RuboCop's plugin system.
#
# pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/plugin.rb:8
class RuboCop::Rubyfmt::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-rubyfmt#lib/rubocop/rubyfmt/version.rb:5
RuboCop::Rubyfmt::VERSION = T.let(T.unsafe(nil), String)
