# typed: true
# frozen_string_literal: true

require "action_view"
require "active_support"
require "benchmark"
require "bundler/setup"
require "code_ownership"
require "code_teams"
require "dogapi"
require "json"
require "minitest/test"
require "pack_stats/gauge_metric"
require "pack_stats/private"
require "pack_stats/private/datadog_reporter"
require "pack_stats/private/metrics"
require "pack_stats/private/metrics/dependencies"
require "pack_stats/private/metrics/files"
require "pack_stats/private/metrics/packages"
require "pack_stats/private/metrics/packages_by_team"
require "pack_stats/private/metrics/packwerk_checker_usage"
require "pack_stats/private/metrics/public_usage"
require "pack_stats/private/source_code_file"
require "pack_stats/tag"
require "pack_stats/tags"
require "packs"
require "packs/rspec/support"
require "parse_packwerk"
require "pathname"
require "pry"
require "rubocop-packs"
require "sorbet-runtime"
require "yaml"
