name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  call-workflow-from-shared-config:
    uses: rubyatscale/shared-config/.github/workflows/ci.yml@main
    secrets: inherit
  rubyfmt:
    name: "Rubyfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Rubyfmt
        uses: rubyatscale/rubyfmt-action@v1
        with:
          paths: |
            lib/
            spec/
            Rakefile
            pack_stats.gemspec
            Gemfile
